# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe2dd085cea884beee5e6d722256a7da17e3acab003601fd7fd9b86835247fe310b5fb05a5f0fb0ffc7fb1248b5c16b5a87fc3d78638e4f0d2607d0b3ce4ca5

test:
  secret_key_base: 660d4a75fc2a55ec48aa640f876edd26f1557a37bef67f4c37750729c4f4340702731d205bf2d09f9c8babc1a5bfd11cfc682a739677f9d3b2a84321887b77e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # use the key below for testing production code
  # secret_key_base: 660d4a75fc2a55ec48aa640f876edd26f1557a37bef67f4c37750729c4f4340702731d205bf2d09f9c8babc1a5bfd11cfc682a739677f9d3b2a84321887b77e6
